# GitGuardian configuration for H-DCN Dashboard
version: 2

# Secret scanning configuration
secret:
  # Show all policy breaks, not just secrets
  show_secrets: false
  
  # Ignore specific patterns that are false positives
  ignore_known_secrets: true

# Exit codes
exit_zero: false  # Return non-zero exit code when secrets are found
