# GitGuardian configuration for H-DCN Dashboard
version: 2

# Paths to exclude from scanning
paths_ignore:
  - "frontend/node_modules/**"
  - "frontend/build/**"
  - "frontend/package-lock.json"
  - "backend/.aws-sam/**"
  - "backend/.venv/**"
  - "**/*.log"
  - ".git/**"
  - "frontend/public/**"
  - "**/*.md"
  - "**/README*"

# Specific secrets to ignore (if needed)
secret:
  # Show all policy breaks, not just secrets
  show_secrets: false
  
  # Ignore specific patterns that are false positives
  ignore_known_secrets: true

# Exit codes
exit_zero: false  # Return non-zero exit code when secrets are found