"""Property-based tests for order confirmation PDF generation."""
import base64
import re
import sys
import os
from unittest.mock import patch, MagicMock

import pytest
from hypothesis import given, settings, assume
from hypothesis import strategies as st

# Add the handler directory to the path so we can import the function directly
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# Add the auth layer source to the path for real auth_utils import
_auth_layer_path = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..', '..', '..', '..', 'layers', 'auth-layer', 'python')
)
sys.path.insert(0, _auth_layer_path)

# Import the real validate_permissions_with_regions BEFORE mocking
from shared.auth_utils import validate_permissions_with_regions as _real_validate_permissions

# Mock the shared auth layer before importing app
sys.modules['shared'] = MagicMock()
sys.modules['shared.auth_utils'] = MagicMock()
sys.modules['shared.maintenance_fallback'] = MagicMock()
sys.modules['weasyprint'] = MagicMock()

from app import fetch_logo_as_data_uri, render_order_html, format_euro, format_dutch_date


# Strategy for valid MIME content type strings (type/subtype format)
mime_types = st.sampled_from([
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/svg+xml',
    'image/webp',
    'image/bmp',
    'image/tiff',
    'application/octet-stream',
    'application/pdf',
    'text/plain',
])


# Feature: order-confirmation-pdf, Property 2: S3 image to data URI round-trip
class TestS3ImageToDataUriRoundTrip:
    """Property 2: S3 image to data URI round-trip

    For any byte sequence and for any valid MIME content type string,
    encoding the bytes to a data URI and then decoding the base64 portion
    of that URI SHALL produce the original byte sequence, and the URI SHALL
    match the format `data:{content_type};base64,{encoded_data}`.

    **Validates: Requirements 3.2**
    """

    @given(
        image_bytes=st.binary(min_size=1, max_size=10000),
        content_type=mime_types,
    )
    @settings(max_examples=100)
    @patch('app.boto3.client')
    def test_data_uri_round_trip(self, mock_boto_client, image_bytes, content_type):
        """For any byte sequence and valid MIME type, encoding to data URI and
        decoding the base64 portion produces the original bytes, and the URI
        matches the expected format.

        **Validates: Requirements 3.2**
        """
        # Arrange: mock S3 to return the generated bytes with the generated content type
        mock_s3 = MagicMock()
        mock_boto_client.return_value = mock_s3
        mock_body = MagicMock()
        mock_body.read.return_value = image_bytes
        mock_s3.get_object.return_value = {
            'ContentType': content_type,
            'Body': mock_body,
        }

        # Act
        result = fetch_logo_as_data_uri('test-bucket', 'test-key')

        # Assert: result is not None
        assert result is not None

        # Assert: URI matches the format data:{content_type};base64,{encoded_data}
        expected_prefix = f"data:{content_type};base64,"
        assert result.startswith(expected_prefix), (
            f"Data URI should start with '{expected_prefix}', got: {result[:80]}"
        )

        # Assert: the full URI matches the regex pattern
        pattern = re.compile(r'^data:[^;]+;base64,[A-Za-z0-9+/]+=*$')
        assert pattern.match(result), (
            f"Data URI does not match expected format: {result[:80]}"
        )

        # Assert: decoding the base64 portion produces the original byte sequence
        encoded_data = result[len(expected_prefix):]
        decoded_bytes = base64.b64decode(encoded_data)
        assert decoded_bytes == image_bytes, (
            f"Round-trip failed: decoded {len(decoded_bytes)} bytes, "
            f"expected {len(image_bytes)} bytes"
        )


# --- Strategies for Property 1 ---

# Roles that grant products_create permission (with appropriate region access)
# System_CRUD and System_User_Management get immediate full access (no region needed)
# Products_CRUD and Webshop_Management need a region role to pass validate_permissions_with_regions
ADMIN_ROLES_FULL_ACCESS = ['System_CRUD', 'System_User_Management']
ADMIN_ROLES_NEED_REGION = ['Products_CRUD', 'Webshop_Management']
ALL_ADMIN_ROLES = ADMIN_ROLES_FULL_ACCESS + ADMIN_ROLES_NEED_REGION

# Region roles that satisfy the region requirement
REGION_ROLES = ['Regio_All', 'Regio_Noord', 'Regio_Zuid', 'Regio_Oost', 'Regio_West']

# All possible roles in the system that do NOT grant products_create
NON_ADMIN_ROLES = [
    'Members_CRUD', 'Members_Read', 'Members_Export',
    'Events_CRUD', 'Events_Read', 'Events_Export',
    'Products_Read', 'Products_Export',
    'Communication_CRUD', 'Communication_Read', 'Communication_Export',
    'Members_Status_Approve',
    'System_Logs_Read',
    'hdcnLeden', 'verzoek_lid',
]

# Email strategy: generates valid email-like strings
email_strategy = st.from_regex(
    r'[a-zA-Z][a-zA-Z0-9_.]{0,20}@[a-zA-Z]{1,10}\.[a-zA-Z]{2,4}', fullmatch=True
)

# Role set strategy: random subset of all roles (including region roles)
role_strategy = st.lists(
    st.sampled_from(ALL_ADMIN_ROLES + NON_ADMIN_ROLES + REGION_ROLES),
    min_size=0,
    max_size=5,
    unique=True
)


def _has_products_create_permission(roles: list) -> bool:
    """
    Determine if a set of roles grants the products_create permission,
    taking into account the region requirement from validate_permissions_with_regions.

    Based on the role-to-permission mapping in auth_utils.py:
    - System_CRUD has wildcard '*' (grants everything, no region needed)
    - System_User_Management gets immediate full access in validate_permissions_with_regions
    - Products_CRUD has 'products_create' (needs region role)
    - Webshop_Management has 'products_create' (needs region role)

    The validate_permissions_with_regions function requires:
    - System_CRUD/System_User_Management: immediate full access
    - Permission roles with region roles: authorized
    - hdcnLeden/verzoek_lid without region: basic member access (authorized but no products_create)
    - Permission roles without region: denied (requires region assignment)
    """
    # System_CRUD or System_User_Management gets immediate full access
    if any(role in ADMIN_ROLES_FULL_ACCESS for role in roles):
        return True

    # Check if user has a permission role that grants products_create
    has_permission_role = any(role in ADMIN_ROLES_NEED_REGION for role in roles)
    if not has_permission_role:
        return False

    # Permission roles need a region role to pass validate_permissions_with_regions
    has_region = any(role in REGION_ROLES for role in roles)
    # hdcnLeden/verzoek_lid count as basic member (pass without region)
    has_basic_member = any(role in ['hdcnLeden', 'verzoek_lid'] for role in roles)

    return has_region or has_basic_member


def _is_authorized(user_email: str, order_email: str, user_roles: list) -> bool:
    """
    Reference implementation of the authorization logic.

    Access is granted if and only if:
    1. The user's email matches the order's user_email (case-insensitive), OR
    2. The user has the products_create permission (via Products_CRUD, Webshop_Management, or System_CRUD)
       with appropriate region access
    """
    email_matches = user_email.lower() == order_email.lower()
    has_permission = _has_products_create_permission(user_roles)
    return email_matches or has_permission


# Feature: order-confirmation-pdf, Property 1: Authorization grants access if and only if user is owner or admin
class TestProperty1AuthorizationGrantsAccess:
    """Property 1: Authorization grants access if and only if user is owner or admin.

    Validates: Requirements 2.2, 2.3, 2.4

    For any order record with an associated user_email, and for any authenticated
    user with an email and set of roles: the PDF generation request SHALL be
    authorized if and only if the user's email matches the order's user_email
    (case-insensitive) OR the user has the products_create permission (via
    Products_CRUD, Webshop_Management, or System_CRUD roles).
    """

    @given(
        user_email=email_strategy,
        order_email=email_strategy,
        user_roles=role_strategy,
    )
    @settings(max_examples=200)
    def test_owner_access_granted_when_emails_match(self, user_email, order_email, user_roles):
        """When user email matches order email (case-insensitive), access is always granted.

        **Validates: Requirements 2.2**
        """
        # Force emails to match (case-insensitive)
        order_email = user_email.upper()

        # The user is the owner, so authorization should always succeed
        assert _is_authorized(user_email, order_email, user_roles) is True

    @given(
        user_email=email_strategy,
        order_email=email_strategy,
        admin_role=st.sampled_from(ALL_ADMIN_ROLES),
        extra_roles=st.lists(st.sampled_from(NON_ADMIN_ROLES + REGION_ROLES), min_size=0, max_size=3, unique=True),
    )
    @settings(max_examples=200)
    def test_admin_access_granted_with_products_create_permission(
        self, user_email, order_email, admin_role, extra_roles
    ):
        """When user has products_create permission (via Products_CRUD, Webshop_Management,
        or System_CRUD), access is always granted regardless of email match.

        **Validates: Requirements 2.3**
        """
        # Ensure emails don't match to isolate the admin permission check
        assume(user_email.lower() != order_email.lower())

        user_roles = [admin_role] + extra_roles

        # If admin_role needs a region, ensure one is present
        if admin_role in ADMIN_ROLES_NEED_REGION:
            if not any(r in REGION_ROLES for r in user_roles):
                user_roles.append('Regio_All')

        # Admin role grants access regardless of email
        assert _is_authorized(user_email, order_email, user_roles) is True

    @given(
        user_email=email_strategy,
        order_email=email_strategy,
        user_roles=st.lists(
            st.sampled_from(NON_ADMIN_ROLES + REGION_ROLES),
            min_size=0, max_size=5, unique=True
        ),
    )
    @settings(max_examples=200)
    def test_access_denied_when_not_owner_and_not_admin(self, user_email, order_email, user_roles):
        """When user email does NOT match order email AND user does NOT have
        products_create permission, access is denied.

        **Validates: Requirements 2.4**
        """
        # Ensure emails don't match
        assume(user_email.lower() != order_email.lower())

        assert _is_authorized(user_email, order_email, user_roles) is False

    @given(
        user_email=email_strategy,
        order_email=email_strategy,
        user_roles=role_strategy,
    )
    @settings(max_examples=200)
    def test_authorization_biconditional_matches_real_auth_layer(
        self, user_email, order_email, user_roles
    ):
        """The authorization decision from the reference implementation matches
        the actual auth layer's validate_permissions_with_regions for the
        products_create permission check.

        This verifies the biconditional: access is granted IF AND ONLY IF
        email matches OR user has products_create permission.

        **Validates: Requirements 2.2, 2.3, 2.4**
        """
        # Check email match (case-insensitive)
        email_matches = user_email.lower() == order_email.lower()

        # Check permission via the real auth layer
        is_perm_authorized, error_response, _ = _real_validate_permissions(
            user_roles, ['products_create'], user_email=user_email
        )

        # The combined authorization decision
        actual_authorized = email_matches or is_perm_authorized

        # Must match our reference implementation
        expected_authorized = _is_authorized(user_email, order_email, user_roles)

        assert actual_authorized == expected_authorized, (
            f"Authorization mismatch: user_email={user_email}, order_email={order_email}, "
            f"roles={user_roles}, email_matches={email_matches}, "
            f"perm_authorized={is_perm_authorized}, expected={expected_authorized}, "
            f"actual={actual_authorized}"
        )


# Import format_dutch_date from app (already on sys.path from the top-level setup)
from datetime import datetime as _datetime
from app import format_dutch_date, DUTCH_MONTHS


# Strategy for generating valid datetimes within a reasonable range
_datetime_strategy = st.datetimes(
    min_value=_datetime(1900, 1, 1),
    max_value=_datetime(2099, 12, 31, 23, 59, 59),
)


# Feature: order-confirmation-pdf, Property 5: Dutch locale date formatting
class TestProperty5DutchLocaleDateFormatting:
    """Property 5: Dutch locale date formatting

    For any valid ISO 8601 timestamp, the formatted date string SHALL contain
    a Dutch month name (januari, februari, ..., december) and include day, year,
    hours, and minutes.

    **Validates: Requirements 4.9**
    """

    @given(dt=_datetime_strategy)
    @settings(max_examples=100)
    def test_dutch_date_contains_dutch_month_name(self, dt):
        """For any valid datetime, the formatted date contains a Dutch month name.

        **Validates: Requirements 4.9**
        """
        iso_timestamp = dt.isoformat()

        result = format_dutch_date(iso_timestamp)

        # The output must contain exactly one Dutch month name
        found_months = [m for m in DUTCH_MONTHS if m in result]
        assert len(found_months) == 1, (
            f"Expected exactly one Dutch month name in '{result}', "
            f"found: {found_months} for input {iso_timestamp}"
        )
        # The found month must correspond to the input month
        expected_month = DUTCH_MONTHS[dt.month - 1]
        assert expected_month in result, (
            f"Expected month '{expected_month}' in '{result}' for input {iso_timestamp}"
        )

    @given(dt=_datetime_strategy)
    @settings(max_examples=100)
    def test_dutch_date_contains_day_number(self, dt):
        """For any valid datetime, the formatted date contains the day number.

        **Validates: Requirements 4.9**
        """
        iso_timestamp = dt.isoformat()

        result = format_dutch_date(iso_timestamp)

        # The output must contain the day number
        assert str(dt.day) in result, (
            f"Expected day '{dt.day}' in '{result}' for input {iso_timestamp}"
        )

    @given(dt=_datetime_strategy)
    @settings(max_examples=100)
    def test_dutch_date_contains_year(self, dt):
        """For any valid datetime, the formatted date contains the year.

        **Validates: Requirements 4.9**
        """
        iso_timestamp = dt.isoformat()

        result = format_dutch_date(iso_timestamp)

        # The output must contain the year
        assert str(dt.year) in result, (
            f"Expected year '{dt.year}' in '{result}' for input {iso_timestamp}"
        )

    @given(dt=_datetime_strategy)
    @settings(max_examples=100)
    def test_dutch_date_contains_hours_and_minutes(self, dt):
        """For any valid datetime, the formatted date contains hours and minutes
        in HH:MM format.

        **Validates: Requirements 4.9**
        """
        iso_timestamp = dt.isoformat()

        result = format_dutch_date(iso_timestamp)

        # The output must contain hours:minutes in HH:MM format
        expected_time = f"{dt.hour:02d}:{dt.minute:02d}"
        assert expected_time in result, (
            f"Expected time '{expected_time}' in '{result}' for input {iso_timestamp}"
        )


# Feature: order-confirmation-pdf, Property 4: Monetary value formatting
class TestProperty4MonetaryValueFormatting:
    """Property 4: Monetary value formatting

    For any numeric string representing a monetary amount, the formatted output
    SHALL be prefixed with the euro symbol (€) and display exactly two decimal
    places (e.g., '€12.50', '€0.00', '€1234.56').

    **Validates: Requirements 4.8**
    """

    @given(value=st.floats(min_value=-1e9, max_value=1e9, allow_nan=False, allow_infinity=False))
    @settings(max_examples=100)
    def test_format_euro_with_floats(self, value):
        """For any finite float value, format_euro SHALL produce output starting
        with '€' and having exactly 2 decimal places.

        **Validates: Requirements 4.8**
        """
        result = format_euro(value)

        # Must start with euro symbol
        assert result.startswith('€'), (
            f"Expected output to start with '€', got: {result!r}"
        )

        # Extract the numeric part after the euro symbol
        numeric_part = result[1:]

        # Must contain exactly one decimal point with exactly 2 digits after it
        assert '.' in numeric_part, (
            f"Expected a decimal point in the numeric part, got: {numeric_part!r}"
        )
        integer_part, decimal_part = numeric_part.rsplit('.', 1)
        assert len(decimal_part) == 2, (
            f"Expected exactly 2 decimal places, got {len(decimal_part)}: {result!r}"
        )

        # The numeric value must be correctly represented (within float precision)
        parsed_value = float(numeric_part)
        expected_value = round(float(value), 2)
        assert parsed_value == expected_value, (
            f"Numeric value mismatch: format_euro({value}) = {result!r}, "
            f"parsed={parsed_value}, expected={expected_value}"
        )

    @given(value=st.integers(min_value=-1000000, max_value=1000000))
    @settings(max_examples=100)
    def test_format_euro_with_integers(self, value):
        """For any integer value, format_euro SHALL produce output starting
        with '€' and having exactly 2 decimal places.

        **Validates: Requirements 4.8**
        """
        result = format_euro(value)

        # Must start with euro symbol
        assert result.startswith('€'), (
            f"Expected output to start with '€', got: {result!r}"
        )

        # Extract the numeric part after the euro symbol
        numeric_part = result[1:]

        # Must contain exactly one decimal point with exactly 2 digits after it
        assert '.' in numeric_part, (
            f"Expected a decimal point in the numeric part, got: {numeric_part!r}"
        )
        integer_part, decimal_part = numeric_part.rsplit('.', 1)
        assert len(decimal_part) == 2, (
            f"Expected exactly 2 decimal places, got {len(decimal_part)}: {result!r}"
        )

        # The numeric value must be correctly represented
        parsed_value = float(numeric_part)
        assert parsed_value == float(value), (
            f"Numeric value mismatch: format_euro({value}) = {result!r}, "
            f"parsed={parsed_value}, expected={float(value)}"
        )

    @given(
        value=st.floats(min_value=0, max_value=1e6, allow_nan=False, allow_infinity=False)
            .map(lambda x: str(round(x, 2)))
    )
    @settings(max_examples=100)
    def test_format_euro_with_numeric_strings(self, value):
        """For any string representing a numeric amount, format_euro SHALL produce
        output starting with '€' and having exactly 2 decimal places.

        **Validates: Requirements 4.8**
        """
        result = format_euro(value)

        # Must start with euro symbol
        assert result.startswith('€'), (
            f"Expected output to start with '€', got: {result!r}"
        )

        # Extract the numeric part after the euro symbol
        numeric_part = result[1:]

        # Must contain exactly one decimal point with exactly 2 digits after it
        assert '.' in numeric_part, (
            f"Expected a decimal point in the numeric part, got: {numeric_part!r}"
        )
        integer_part, decimal_part = numeric_part.rsplit('.', 1)
        assert len(decimal_part) == 2, (
            f"Expected exactly 2 decimal places, got {len(decimal_part)}: {result!r}"
        )

        # The numeric value must be correctly represented
        parsed_value = float(numeric_part)
        expected_value = round(float(value), 2)
        assert parsed_value == expected_value, (
            f"Numeric value mismatch: format_euro({value!r}) = {result!r}, "
            f"parsed={parsed_value}, expected={expected_value}"
        )

    @given(value=st.text(min_size=1, max_size=20).filter(lambda s: not _is_numeric(s)))
    @settings(max_examples=100)
    def test_format_euro_with_non_numeric_strings_defaults_to_zero(self, value):
        """For any non-numeric string, format_euro SHALL default to '€0.00'.

        **Validates: Requirements 4.8**
        """
        result = format_euro(value)

        # Must start with euro symbol
        assert result.startswith('€'), (
            f"Expected output to start with '€', got: {result!r}"
        )

        # Non-numeric input should default to €0.00
        assert result == '€0.00', (
            f"Expected '€0.00' for non-numeric input {value!r}, got: {result!r}"
        )


def _is_numeric(s: str) -> bool:
    """Helper to check if a string can be converted to float."""
    try:
        float(s)
        return True
    except (TypeError, ValueError):
        return False


# --- Strategies for Property 3 ---

from decimal import Decimal

# Strategy for non-empty printable text (no HTML-breaking characters)
_safe_text = st.text(
    alphabet=st.characters(whitelist_categories=('L', 'N', 'Zs'), whitelist_characters='-_.'),
    min_size=1,
    max_size=30,
).filter(lambda s: s.strip() != '')

# Strategy for monetary amount strings (e.g. "12.50", "0.00", "1234.99")
_money_amount = st.decimals(
    min_value=Decimal('0.00'), max_value=Decimal('9999.99'), places=2, allow_nan=False, allow_infinity=False
).map(lambda d: f"{d:.2f}")

# Strategy for ISO 8601 timestamps
_iso_timestamp = st.builds(
    lambda y, mo, d, h, mi: f"{y:04d}-{mo:02d}-{d:02d}T{h:02d}:{mi:02d}:00Z",
    y=st.integers(min_value=2020, max_value=2030),
    mo=st.integers(min_value=1, max_value=12),
    d=st.integers(min_value=1, max_value=28),
    h=st.integers(min_value=0, max_value=23),
    mi=st.integers(min_value=0, max_value=59),
)

# Strategy for a single order item
_order_item = st.fixed_dictionaries({
    'quantity': st.integers(min_value=1, max_value=100),
    'price': st.decimals(min_value=Decimal('0.01'), max_value=Decimal('999.99'), places=2, allow_nan=False, allow_infinity=False).map(float),
}).flatmap(lambda base: st.one_of(
    # Item with 'name' key
    st.fixed_dictionaries({
        'name': _safe_text,
        'quantity': st.just(base['quantity']),
        'price': st.just(base['price']),
        'selectedOption': st.one_of(st.none(), _safe_text),
    }),
    # Item with 'naam' key
    st.fixed_dictionaries({
        'naam': _safe_text,
        'quantity': st.just(base['quantity']),
        'price': st.just(base['price']),
        'selectedOption': st.one_of(st.none(), _safe_text),
    }),
))

# Strategy for customer_info
_customer_info = st.fixed_dictionaries({
    'name': _safe_text,
    'straat': _safe_text,
    'postcode': st.from_regex(r'[1-9][0-9]{3}[A-Z]{2}', fullmatch=True),
    'woonplaats': _safe_text,
}, optional={
    'email': st.emails(),
    'phone': st.from_regex(r'06[0-9]{8}', fullmatch=True),
})

# Strategy for delivery_option
_delivery_option = st.fixed_dictionaries({
    'label': _safe_text,
})

# Strategy for a complete valid order record
_order_record = st.fixed_dictionaries({
    'order_id': st.from_regex(r'ORD-[A-Z0-9]{6,12}', fullmatch=True),
    'timestamp': _iso_timestamp,
    'customer_info': _customer_info,
    'items': st.lists(_order_item, min_size=1, max_size=10),
    'subtotal_amount': _money_amount,
    'total_amount': _money_amount,
}).flatmap(lambda order: st.one_of(
    # Order without delivery option
    st.just(order),
    # Order with delivery option
    st.builds(
        lambda o, opt, cost: {**o, 'delivery_option': opt, 'delivery_cost': cost},
        o=st.just(order),
        opt=_delivery_option,
        cost=_money_amount,
    ),
))

# Strategy for logo data URI (optional)
_logo_data_uri = st.one_of(
    st.none(),
    st.binary(min_size=10, max_size=200).map(
        lambda b: f"data:image/png;base64,{base64.b64encode(b).decode('utf-8')}"
    ),
)


# Feature: order-confirmation-pdf, Property 3: Template data completeness
class TestProperty3TemplateDataCompleteness:
    """Property 3: Template data completeness

    For any valid order record, the rendered HTML template SHALL contain:
    - The order_id
    - The formatted order date
    - All customer_info fields that are present (name, straat, postcode, woonplaats,
      and conditionally email and phone)
    - Each item's name (or naam), quantity, and price
    - The subtotal_amount and total_amount
    - The delivery option label and cost (if delivery_option is present)
    - The logo data URI as an img src attribute (if logo was successfully fetched)

    **Validates: Requirements 3.3, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7**
    """

    @given(
        order=_order_record,
        logo_data_uri=_logo_data_uri,
    )
    @settings(max_examples=100)
    def test_template_contains_all_order_data(self, order, logo_data_uri):
        """For any valid order record, the rendered HTML contains all expected data fields.

        **Validates: Requirements 3.3, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7**
        """
        html = render_order_html(order, logo_data_uri)

        # 1. The order_id must appear in the HTML
        assert order['order_id'] in html, (
            f"order_id '{order['order_id']}' not found in rendered HTML"
        )

        # 2. The formatted order date must appear
        formatted_date = format_dutch_date(order['timestamp'])
        assert formatted_date in html, (
            f"Formatted date '{formatted_date}' not found in rendered HTML"
        )

        # 3. All customer_info fields that are present
        customer_info = order['customer_info']
        assert customer_info['name'] in html, (
            f"Customer name '{customer_info['name']}' not found in rendered HTML"
        )
        assert customer_info['straat'] in html, (
            f"Customer straat '{customer_info['straat']}' not found in rendered HTML"
        )
        assert customer_info['postcode'] in html, (
            f"Customer postcode '{customer_info['postcode']}' not found in rendered HTML"
        )
        assert customer_info['woonplaats'] in html, (
            f"Customer woonplaats '{customer_info['woonplaats']}' not found in rendered HTML"
        )

        # Conditionally: email and phone
        if 'email' in customer_info and customer_info['email']:
            assert customer_info['email'] in html, (
                f"Customer email '{customer_info['email']}' not found in rendered HTML"
            )
        if 'phone' in customer_info and customer_info['phone']:
            assert customer_info['phone'] in html, (
                f"Customer phone '{customer_info['phone']}' not found in rendered HTML"
            )

        # 4. Each item's name (or naam), quantity, and price
        for item in order['items']:
            item_name = item.get('name') or item.get('naam', '')
            assert item_name in html, (
                f"Item name '{item_name}' not found in rendered HTML"
            )
            assert str(item['quantity']) in html, (
                f"Item quantity '{item['quantity']}' not found in rendered HTML"
            )
            assert format_euro(item['price']) in html, (
                f"Item price '{format_euro(item['price'])}' not found in rendered HTML"
            )

        # 5. The subtotal_amount and total_amount
        assert format_euro(order['subtotal_amount']) in html, (
            f"Subtotal '{format_euro(order['subtotal_amount'])}' not found in rendered HTML"
        )
        assert format_euro(order['total_amount']) in html, (
            f"Total '{format_euro(order['total_amount'])}' not found in rendered HTML"
        )

        # 6. Delivery option label and cost (if present)
        if 'delivery_option' in order and order['delivery_option']:
            delivery_label = order['delivery_option']['label']
            assert delivery_label in html, (
                f"Delivery label '{delivery_label}' not found in rendered HTML"
            )
        if 'delivery_cost' in order and order['delivery_cost']:
            assert format_euro(order['delivery_cost']) in html, (
                f"Delivery cost '{format_euro(order['delivery_cost'])}' not found in rendered HTML"
            )

        # 7. Logo data URI as img src attribute (if provided)
        if logo_data_uri is not None:
            assert f'src="{logo_data_uri}"' in html, (
                f"Logo data URI not found as img src in rendered HTML"
            )
        else:
            # When no logo is provided, no img element with data URI should appear
            assert 'data:image' not in html, (
                "Unexpected data URI found in HTML when no logo was provided"
            )


# Feature: order-confirmation-pdf, Property 6: Valid PDF generation for any order
class TestProperty6ValidPdfGeneration:
    """Property 6: Valid PDF generation for any order

    For any valid order record (with order_id, timestamp, items, subtotal_amount,
    total_amount), the Lambda SHALL produce a response with HTTP 200,
    Content-Type: application/pdf, a Content-Disposition header containing
    orderbevestiging-{order_id}.pdf, and a body that when base64-decoded starts
    with the %PDF magic bytes and has non-zero length.

    **Validates: Requirements 1.2, 1.3, 5.2**
    """

    @given(order=_order_record)
    @settings(max_examples=20)
    @patch('app.boto3.client')
    @patch('app.boto3.resource')
    @patch('app.extract_user_credentials')
    @patch('app.log_successful_access')
    @patch('app.cors_headers', return_value={'Access-Control-Allow-Origin': '*'})
    def test_valid_pdf_generation_for_any_order(
        self, mock_cors, mock_log, mock_extract_creds, mock_boto_resource, mock_boto_client, order
    ):
        """For any valid order record, the lambda_handler SHALL return HTTP 200
        with Content-Type application/pdf, Content-Disposition containing
        orderbevestiging-{order_id}.pdf, isBase64Encoded True, and a body that
        when base64-decoded starts with %PDF magic bytes and has non-zero length.

        **Validates: Requirements 1.2, 1.3, 5.2**
        """
        from app import lambda_handler

        order_id = order['order_id']

        # Add user_email to order for ownership check
        user_email = 'testuser@example.com'
        order_with_email = {**order, 'user_email': user_email}

        # Mock auth: return valid user credentials
        mock_extract_creds.return_value = (user_email, ['System_CRUD'], None)

        # Mock DynamoDB: return the generated order
        mock_table = MagicMock()
        mock_table.get_item.return_value = {'Item': order_with_email}
        mock_dynamodb = MagicMock()
        mock_dynamodb.Table.return_value = mock_table
        mock_boto_resource.return_value = mock_dynamodb

        # Mock S3: logo fetch returns None (graceful degradation)
        mock_s3 = MagicMock()
        mock_s3.get_object.side_effect = Exception("S3 unavailable")
        mock_boto_client.return_value = mock_s3

        # Mock WeasyPrint: return fake PDF bytes starting with %PDF
        fake_pdf_bytes = b'%PDF-1.4 fake pdf content for testing purposes'
        mock_weasyprint_html = MagicMock()
        mock_weasyprint_html.return_value.write_pdf.return_value = fake_pdf_bytes

        with patch('app.weasyprint') as mock_wp:
            mock_wp.HTML = mock_weasyprint_html

            # Build API Gateway event
            event = {
                'httpMethod': 'GET',
                'pathParameters': {'order_id': order_id},
                'headers': {'Authorization': 'Bearer fake-jwt-token'},
            }

            # Act
            response = lambda_handler(event, None)

        # Assert 1: Response statusCode is 200
        assert response['statusCode'] == 200, (
            f"Expected statusCode 200, got {response['statusCode']} "
            f"for order_id={order_id}"
        )

        # Assert 2: Content-Type header is "application/pdf"
        headers = response.get('headers', {})
        assert headers.get('Content-Type') == 'application/pdf', (
            f"Expected Content-Type 'application/pdf', got "
            f"'{headers.get('Content-Type')}' for order_id={order_id}"
        )

        # Assert 3: Content-Disposition header contains "orderbevestiging-{order_id}.pdf"
        content_disposition = headers.get('Content-Disposition', '')
        expected_filename = f'orderbevestiging-{order_id}.pdf'
        assert expected_filename in content_disposition, (
            f"Expected '{expected_filename}' in Content-Disposition header, "
            f"got '{content_disposition}'"
        )

        # Assert 4: isBase64Encoded is True
        assert response.get('isBase64Encoded') is True, (
            f"Expected isBase64Encoded=True, got {response.get('isBase64Encoded')}"
        )

        # Assert 5: Body when base64-decoded starts with %PDF magic bytes
        body = response.get('body', '')
        decoded_body = base64.b64decode(body)
        assert decoded_body[:4] == b'%PDF', (
            f"Expected decoded body to start with b'%PDF', "
            f"got {decoded_body[:10]!r} for order_id={order_id}"
        )

        # Assert 6: Body has non-zero length
        assert len(decoded_body) > 0, (
            f"Expected non-zero body length, got 0 for order_id={order_id}"
        )


# ============================================================================
# NEW PROPERTY TESTS: Frontend-matching layout properties
# ============================================================================

# Import the new helper functions
from app import (
    build_css, build_header_html, build_addresses_html,
    build_products_table_html, build_totals_html, _resolve_customer_name,
)


# Strategy for customer_info with name fallback variations
_customer_info_with_name = st.fixed_dictionaries({
    'name': _safe_text,
    'straat': _safe_text,
    'postcode': st.from_regex(r'[1-9][0-9]{3} [A-Z]{2}', fullmatch=True),
    'woonplaats': _safe_text,
}, optional={
    'email': st.emails(),
    'phone': st.from_regex(r'06-[0-9]{8}', fullmatch=True),
})

_customer_info_without_name = st.fixed_dictionaries({
    'voornaam': _safe_text,
    'achternaam': _safe_text,
    'straat': _safe_text,
    'postcode': st.from_regex(r'[1-9][0-9]{3} [A-Z]{2}', fullmatch=True),
    'woonplaats': _safe_text,
})

_any_customer_info = st.one_of(_customer_info_with_name, _customer_info_without_name)

# Strategy for shipping_address
_shipping_address = st.one_of(
    st.none(),
    st.fixed_dictionaries({
        'name': _safe_text,
        'straat': _safe_text,
        'postcode': st.from_regex(r'[1-9][0-9]{3} [A-Z]{2}', fullmatch=True),
        'woonplaats': _safe_text,
    }),
)


class TestPropertyOrangeBranding:
    """Property 2: Orange branding and absence of old color scheme.

    For any valid order dict, the output of render_order_html() contains
    #FF6B35 and does NOT contain #2c3e50.

    **Validates: Requirements 1.1, 1.2**
    """

    @given(order=_order_record, logo=_logo_data_uri)
    @settings(max_examples=50)
    def test_orange_branding_present_old_scheme_absent(self, order, logo):
        """Output contains #FF6B35 and NOT #2c3e50."""
        html = render_order_html(order, logo)

        assert '#FF6B35' in html, "Orange branding #FF6B35 missing from output"
        assert '#2c3e50' not in html, "Old dark blue #2c3e50 still present in output"


class TestPropertyTwoColumnAddressLayout:
    """Property 3: Two-column address layout.

    For any order with customer_info, the output HTML contains both
    "Factuuradres" and "Verzendadres".

    **Validates: Requirements 3.1**
    """

    @given(order=_order_record, logo=_logo_data_uri)
    @settings(max_examples=50)
    def test_both_address_sections_present(self, order, logo):
        """Output contains both Factuuradres and Verzendadres."""
        html = render_order_html(order, logo)

        assert 'Factuuradres' in html, "Factuuradres section missing"
        assert 'Verzendadres' in html, "Verzendadres section missing"


class TestPropertyTableHeaderStyling:
    """Property 4: Table header styling and alignment.

    For any order with at least one item, the output HTML contains #F9FAFB
    as table header background and right-aligned numeric columns.

    **Validates: Requirements 4.1, 4.3**
    """

    @given(order=_order_record, logo=_logo_data_uri)
    @settings(max_examples=50)
    def test_light_grey_header_and_right_alignment(self, order, logo):
        """Table header uses #F9FAFB and numeric columns are right-aligned."""
        assume(len(order.get('items', [])) > 0)

        html = render_order_html(order, logo)

        assert '#F9FAFB' in html, "Light grey header color #F9FAFB missing"
        assert 'text-align: right' in html, "Right alignment for numeric columns missing"
        assert 'class="right"' in html, "Right-aligned td/th class missing"


class TestPropertyTotaalBetaald:
    """Property 5: Totaal betaald presentation.

    For any order, the output HTML contains "Totaal betaald" with font-size
    18px and font-weight bold.

    **Validates: Requirements 5.1**
    """

    @given(order=_order_record, logo=_logo_data_uri)
    @settings(max_examples=50)
    def test_totaal_betaald_styled_correctly(self, order, logo):
        """'Totaal betaald' appears with 18px bold styling."""
        html = render_order_html(order, logo)

        assert 'Totaal betaald' in html, "'Totaal betaald' text missing"
        # The CSS class totals-final has font-size: 18px and font-weight: bold
        assert 'totals-final' in html, "totals-final CSS class missing"
        css = build_css()
        assert '18px' in css, "18px font-size missing from CSS"
        assert 'font-weight: bold' in css, "font-weight: bold missing from CSS"


class TestPropertyDeliverySectionPosition:
    """Property 6: Delivery section position.

    For any order with a delivery_option, the delivery section HTML appears
    BEFORE the products table HTML in the output string.

    **Validates: Requirements 6.1**
    """

    @given(
        order=_order_record.filter(lambda o: 'delivery_option' in o and o['delivery_option'] is not None),
        logo=_logo_data_uri,
    )
    @settings(max_examples=50)
    def test_delivery_before_products_table(self, order, logo):
        """Delivery section appears before the products table."""
        html = render_order_html(order, logo)

        delivery_label = order['delivery_option']['label']
        assert delivery_label in html, f"Delivery label '{delivery_label}' not in output"

        delivery_pos = html.index(delivery_label)
        products_pos = html.index('Bestelde producten')
        assert delivery_pos < products_pos, (
            f"Delivery section (pos {delivery_pos}) not before products table (pos {products_pos})"
        )


class TestPropertyAmountFormatting:
    """Property 7: Amount formatting with euro symbol and two decimals.

    For every amount in the order, the formatted output uses €X.XX format.

    **Validates: Requirements 5.2**
    """

    @given(order=_order_record, logo=_logo_data_uri)
    @settings(max_examples=50)
    def test_all_amounts_use_euro_format(self, order, logo):
        """All monetary amounts are formatted as €X.XX."""
        html = render_order_html(order, logo)

        # Subtotal and total must appear formatted
        assert format_euro(order['subtotal_amount']) in html, (
            f"Subtotal {format_euro(order['subtotal_amount'])} not found"
        )
        assert format_euro(order['total_amount']) in html, (
            f"Total {format_euro(order['total_amount'])} not found"
        )

        # Delivery cost if present
        if 'delivery_cost' in order and order['delivery_cost']:
            assert format_euro(order['delivery_cost']) in html, (
                f"Delivery cost {format_euro(order['delivery_cost'])} not found"
            )

        # Item prices
        for item in order['items']:
            assert format_euro(item['price']) in html, (
                f"Item price {format_euro(item['price'])} not found"
            )


class TestPropertyCustomerNameResolution:
    """Property 8: Customer name resolution.

    For orders with customer_info containing a 'name' field, that name appears
    in the output. For orders with voornaam+achternaam, the combined name appears.

    **Validates: Requirements 8.1, 8.2**
    """

    @given(customer_info=_customer_info_with_name)
    @settings(max_examples=50)
    def test_name_field_used_when_present(self, customer_info):
        """When 'name' field is present, it appears in the output."""
        order = {
            'order_id': 'ORD-TEST001',
            'items': [],
            'customer_info': customer_info,
        }
        html = render_order_html(order)

        assert customer_info['name'] in html, (
            f"Customer name '{customer_info['name']}' not found in output"
        )

    @given(customer_info=_customer_info_without_name)
    @settings(max_examples=50)
    def test_voornaam_achternaam_combined_when_no_name(self, customer_info):
        """When no 'name' field, voornaam+achternaam are combined."""
        order = {
            'order_id': 'ORD-TEST002',
            'items': [],
            'customer_info': customer_info,
        }
        html = render_order_html(order)

        expected_name = f"{customer_info['voornaam']} {customer_info['achternaam']}"
        assert expected_name in html, (
            f"Combined name '{expected_name}' not found in output"
        )

    def test_niet_beschikbaar_when_no_name_info(self):
        """When no name fields at all, 'Niet beschikbaar' is shown."""
        order = {
            'order_id': 'ORD-TEST003',
            'items': [],
            'customer_info': {'straat': 'Teststraat 1'},
        }
        html = render_order_html(order)

        assert 'Niet beschikbaar' in html


class TestPropertyWeasyPrintCompatibility:
    """Property 9: WeasyPrint CSS compatibility.

    For any generated HTML, the output does not contain 'display: flex' for
    layout structures and does contain an @page directive with A4 size.

    **Validates: Requirements 7.1, 7.3**
    """

    @given(order=_order_record, logo=_logo_data_uri)
    @settings(max_examples=50)
    def test_no_flex_layout_and_has_a4_page(self, order, logo):
        """No display:flex in output, @page with A4 is present."""
        html = render_order_html(order, logo)

        assert 'display: flex' not in html, "display: flex found (WeasyPrint incompatible)"
        assert 'display:flex' not in html, "display:flex found (WeasyPrint incompatible)"
        assert '@page' in html, "@page directive missing"
        assert 'A4' in html, "A4 page size missing"
        assert '20mm' in html, "20mm margin missing"


class TestEdgeCases:
    """Unit tests for edge cases.

    **Validates: Requirements 8.3, 9.2, 9.3**
    """

    def test_empty_order_no_items_no_customer(self):
        """Minimal order with no items and no customer_info renders."""
        order = {'order_id': 'ORD-EMPTY', 'items': []}
        html = render_order_html(order)

        assert '<!DOCTYPE html>' in html
        assert 'ORD-EMPTY' in html
        assert 'Niet beschikbaar' in html

    def test_order_without_logo(self):
        """Order without logo_data_uri doesn't include img tag."""
        order = {'order_id': 'ORD-NOLOGO', 'items': [{'name': 'Test', 'quantity': 1, 'price': 10}]}
        html = render_order_html(order, None)

        assert '<img' not in html

    def test_item_with_naam_instead_of_name(self):
        """Item with 'naam' field (Dutch) renders correctly."""
        order = {
            'order_id': 'ORD-NAAM',
            'items': [{'naam': 'Nederlands Product', 'quantity': 3, 'price': 12.50}],
            'customer_info': {'name': 'Test User'},
        }
        html = render_order_html(order)

        assert 'Nederlands Product' in html

    def test_item_without_selected_option(self):
        """Item without selectedOption shows '-' in the option column."""
        order = {
            'order_id': 'ORD-NOOPT',
            'items': [{'name': 'Simple Product', 'quantity': 1, 'price': 20.00}],
            'customer_info': {'name': 'Test'},
        }
        html = render_order_html(order)

        # The '-' should appear in a table cell
        assert '<td>-</td>' in html

    def test_customer_name_fallback_voornaam_achternaam(self):
        """Customer without 'name' but with voornaam+achternaam shows combined name."""
        order = {
            'order_id': 'ORD-FALLBACK',
            'items': [],
            'customer_info': {'voornaam': 'Pieter', 'achternaam': 'Bakker'},
        }
        html = render_order_html(order)

        assert 'Pieter Bakker' in html

    def test_shipping_address_used_when_present(self):
        """When shipping_address is provided, it appears in the Verzendadres section."""
        order = {
            'order_id': 'ORD-SHIP',
            'items': [],
            'customer_info': {'name': 'Billing Name', 'straat': 'Billing St 1'},
            'shipping_address': {'name': 'Shipping Name', 'straat': 'Shipping St 2'},
        }
        html = render_order_html(order)

        assert 'Billing Name' in html
        assert 'Shipping Name' in html
        assert 'Shipping St 2' in html

    def test_no_delivery_option_hides_delivery_section(self):
        """Order without delivery_option does not show delivery section content."""
        order = {
            'order_id': 'ORD-NODELIV',
            'items': [{'name': 'Product', 'quantity': 1, 'price': 10}],
            'customer_info': {'name': 'Test'},
        }
        html = render_order_html(order)

        # The delivery content (title text "Levering" as an HTML element) should not appear
        assert '<div class="delivery">' not in html
        assert '>Levering<' not in html
